name       : python-pynest2d
version    : 4.10.0
release    : 4
source     :
    - https://github.com/Ultimaker/pynest2d/archive/4.10.0.tar.gz : 97babd182f2bab75c0519ac79ead7ac4fc34b8a16de0569b5d2a7d2f7c3592ef
homepage   : https://github.com/Ultimaker/pynest2d
license    : LGPL-3.0-or-later
component  : programming.python
summary    : Python bindings for libnest2d
description: |
    CPython bindings for libnest2d, a library to pack 2D polygons into a small space.
builddeps  :
    - pkgconfig(python3)
    - libnest2d
    - python-sip
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
