name       : python-pynest2d
version    : 4.8.0
release    : 1
source     :
    - https://github.com/Ultimaker/pynest2d/archive/4.8.0.tar.gz : 7ebc1cf881a8686dcbf7a382e47caecd70fbd6e1eb975ce8a4d41b53ef485ab7
license    : LGPL-3.0-or-later
component  : programming.python
summary    :  Python bindings for libnest2d
description: |
    CPython bindings for libnest2d, a library to pack 2D polygons into a small space.
builddeps  :
    - pkgconfig(python3)
    - libnest2d
    - python3-sip-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
